environments:
  - name: e1
    channel: ch1
    users: []
  - name: e2
    channel: ch2
    users:
      - john.doe
      - mary.foo

logging:
  file: kubot.log
  level: INFO

slackToken: some-token

commandConfig:
  productRepo: repo
  deployTimeoutSeconds: 900
  chartFile: chart

commands:
  - name: deploy
    commands:
      - name: "echo"
        args:
          - "deploy"
          - "${productRepo}/${product}"
          - "--version"
          - "${version}"
          - "--timeout"
          - "${deployTimeoutSeconds}"
          - "-f"
          - "${chartFile}"
